import {
  PatSatu,
  PatDua,
  PatTiga,
  PatEmpat,
  PatLima,
  PatEnam,
  PatTujuh,
  PatLapan,
  PatBilan,
  PatSepuluh,
  PatDuap,
  PatTigap,
  PatEmpatp,
  PatLimap,
  PatEnamp,
  PatTujuhp,
  PatLapanp,
  PatBilanp,
  PatRatus,
  PatCalcu,
} from '../../../../assets/Images/Numbers';

const data = [
  {
    title: 'Satu',
    voice: 'Satu',
    image: PatSatu,
    content: [],
  },
  {
    title: 'Dua',
    voice: 'Dua',
    image: PatDua,
    content: [],
  },
  {
    title: 'Tiga',
    voice: 'Tiga',
    image: PatTiga,
    content: [],
  },
  {
    title: 'Empat',
    voice: 'Empat',
    image: PatEmpat,
    content: [],
  },
  {
    title: 'Lima',
    voice: 'Lima',
    image: PatLima,
    content: [],
  },
  {
    title: 'Enam',
    voice: 'Enam',
    image: PatEnam,
    content: [],
  },
  {
    title: 'Tujuh',
    voice: 'Tujuh',
    image: PatTujuh,
    content: [],
  },
  {
    title: 'Delapan',
    voice: 'Delapan',
    image: PatLapan,
    content: [],
  },
  {
    title: 'Sembilan',
    voice: 'Sembilan',
    image: PatBilan,
    content: [],
  },
  {
    title: 'Sepuluh',
    voice: 'Sepuluh',
    image: PatSepuluh,
    content: [],
  },
  {
    title: 'Dua Puluh',
    voice: 'Dua Puluh',
    image: PatDuap,
    content: [],
  },
  {
    title: 'Tiga Puluh',
    voice: 'Tiga Puluh',
    image: PatTigap,
    content: [],
  },
  {
    title: 'Empat Puluh',
    voice: 'Empat Puluh',
    image: PatEmpatp,
    content: [],
  },
  {
    title: 'Lima Puluh',
    voice: 'Lima Puluh',
    image: PatLimap,
    content: [],
  },
  {
    title: 'Enam Puluh',
    voice: 'Enam Puluh',
    image: PatEnamp,
    content: [],
  },
  {
    title: 'Tujuh Puluh',
    voice: 'Tujuh Puluh',
    image: PatTujuhp,
    content: [],
  },
  {
    title: 'Delapan Puluh',
    voice: 'Delapan Puluh',
    image: PatLapanp,
    content: [],
  },
  {
    title: 'Sembilan Puluh',
    voice: 'Sembilan Puluh',
    image: PatBilanp,
    content: [],
  },
  {
    title: 'Seratus',
    voice: 'Seratus',
    image: PatRatus,
    content: [],
  },
  {
    title: 'Kalkulator',
    voice: 'Kalkulator',
    image: PatCalcu,
    content: [],
  },
];

export default data;
